/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPipelineIndexRouteImport } from './routes/_app/pipeline/index'
import { Route as AppFlowsIndexRouteImport } from './routes/_app/flows/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as AppPipelinePipelineIdRouteImport } from './routes/_app/pipeline/$pipelineId'
import { Route as AppFlowsFlowIdRouteImport } from './routes/_app/flows/$flowId'
import { Route as AppContactsContactIdRouteImport } from './routes/_app/contacts/$contactId'
import { Route as ApiWebhooksFlowFlowIdRouteImport } from './routes/api/webhooks/flow.$flowId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineIndexRoute = AppPipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsIndexRoute = AppFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPipelinePipelineIdRoute = AppPipelinePipelineIdRouteImport.update({
  id: '/pipeline/$pipelineId',
  path: '/pipeline/$pipelineId',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsFlowIdRoute = AppFlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksFlowFlowIdRoute = ApiWebhooksFlowFlowIdRouteImport.update({
  id: '/api/webhooks/flow/$flowId',
  path: '/api/webhooks/flow/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/pipeline/$pipelineId': typeof AppPipelinePipelineIdRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/flows/': typeof AppFlowsIndexRoute
  '/pipeline/': typeof AppPipelineIndexRoute
  '/api/webhooks/flow/$flowId': typeof ApiWebhooksFlowFlowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/pipeline/$pipelineId': typeof AppPipelinePipelineIdRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/contacts': typeof AppContactsIndexRoute
  '/flows': typeof AppFlowsIndexRoute
  '/pipeline': typeof AppPipelineIndexRoute
  '/api/webhooks/flow/$flowId': typeof ApiWebhooksFlowFlowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/_app/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/_app/pipeline/$pipelineId': typeof AppPipelinePipelineIdRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/flows/': typeof AppFlowsIndexRoute
  '/_app/pipeline/': typeof AppPipelineIndexRoute
  '/api/webhooks/flow/$flowId': typeof ApiWebhooksFlowFlowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/contacts/$contactId'
    | '/flows/$flowId'
    | '/pipeline/$pipelineId'
    | '/api/webhooks/whatsapp'
    | '/contacts/'
    | '/flows/'
    | '/pipeline/'
    | '/api/webhooks/flow/$flowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/contacts/$contactId'
    | '/flows/$flowId'
    | '/pipeline/$pipelineId'
    | '/api/webhooks/whatsapp'
    | '/contacts'
    | '/flows'
    | '/pipeline'
    | '/api/webhooks/flow/$flowId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/contacts/$contactId'
    | '/_app/flows/$flowId'
    | '/_app/pipeline/$pipelineId'
    | '/api/webhooks/whatsapp'
    | '/_app/contacts/'
    | '/_app/flows/'
    | '/_app/pipeline/'
    | '/api/webhooks/flow/$flowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
  ApiWebhooksFlowFlowIdRoute: typeof ApiWebhooksFlowFlowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline/': {
      id: '/_app/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof AppPipelineIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows/': {
      id: '/_app/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof AppFlowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pipeline/$pipelineId': {
      id: '/_app/pipeline/$pipelineId'
      path: '/pipeline/$pipelineId'
      fullPath: '/pipeline/$pipelineId'
      preLoaderRoute: typeof AppPipelinePipelineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows/$flowId': {
      id: '/_app/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof AppFlowsFlowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/$contactId': {
      id: '/_app/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/flow/$flowId': {
      id: '/api/webhooks/flow/$flowId'
      path: '/api/webhooks/flow/$flowId'
      fullPath: '/api/webhooks/flow/$flowId'
      preLoaderRoute: typeof ApiWebhooksFlowFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppFlowsFlowIdRoute: typeof AppFlowsFlowIdRoute
  AppPipelinePipelineIdRoute: typeof AppPipelinePipelineIdRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppFlowsIndexRoute: typeof AppFlowsIndexRoute
  AppPipelineIndexRoute: typeof AppPipelineIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppFlowsFlowIdRoute: AppFlowsFlowIdRoute,
  AppPipelinePipelineIdRoute: AppPipelinePipelineIdRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppFlowsIndexRoute: AppFlowsIndexRoute,
  AppPipelineIndexRoute: AppPipelineIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
  ApiWebhooksFlowFlowIdRoute: ApiWebhooksFlowFlowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
